spring.application.name=imperial-time-backend

# Server Configuration
server.port=8084

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/imperialdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=imperialuser
spring.datasource.password=Sam@2003

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Spring Security
spring.security.filter.dispatcher-types=REQUEST,ERROR,FORWARD,INCLUDE

# Logging
logging.level.root=INFO
logging.level.com.imperialtime=DEBUG
logging.level.org.springframework.security=DEBUG
